FROM centos:7
MAINTAINER Karim Boumedhel <karimboumedhel@gmail.com>

RUN yum -y install epel-release && yum -y install python-pip && yum clean all && rm -rf /var/cache/yum
RUN pip install -U setuptools && pip install openshift %% pip install Jinja2
